import mongoose from 'mongoose'

const Schema = mongoose.Schema;

const foodSpuTagsSchema = new mongoose.Schema({
    id:Number,
    tag: String,
    restaurant_id: Number,      //餐馆id
    name:String,
    icon:String,                //icon 图片地址
    big_pic_url:String,
    current_page:Number,
    has_next_page:Boolean,
    product_count:Number,
    type:Number,
    selected:Number,
    tag_description:String,
    description:String,
    sequence:Number,
    activity_tag:String,
    tags:[],
    buzType:Number
});

const FoodSpuTags = mongoose.model('FoodSpuTags', foodSpuTagsSchema);


let arr =[
    {
        "id":1,
        "tag": "100",
        "name": "热销",
        "icon": "http://p1.meituan.net/aichequan/87f966955f693102d67daf2ec44b58411361.png",
        "big_pic_url": "",
        "current_page": 0,
        "has_next_page": false,
        "product_count": 0,
        "type": 3,
        "selected": 0,
        "tag_description": "",
        "description": "",
        "sequence": 0,
        "activity_tag": "",
        "tags": [],
        "buzType": 0,
        "restaurant_id": 2203206
    },
    {
        "id":2,
        "tag": "act17",
        "name": "折扣",
        "icon": "http://p0.meituan.net/aichequan/45662b4d1968fd75bff38de23f6d62641421.png",
        "big_pic_url": "",
        "current_page": 0,
        "has_next_page": false,
        "product_count": 3,
        "type": 2,
        "selected": 0,
        "tag_description": "折扣商品",
        "description": "超过限购份数可原价购买",
        "sequence": 1,
        "activity_tag": "discount",
        "tags": [],
        "buzType": 0,
        "restaurant_id": 2203206
    },
    {
        "id":3,
        "tag": "act23",
        "name": "买赠",
        "icon": "http://p0.meituan.net/xianfu/38a500258e860e6b67ff99f6752624782048.png",
        "big_pic_url": "",
        "current_page": 0,
        "has_next_page": false,
        "product_count": 1,
        "type": 2,
        "selected": 0,
        "tag_description": "买赠",
        "description": "",
        "sequence": 3,
        "activity_tag": "buy_donation",
        "tags": [],
        "buzType": 0,
        "restaurant_id": 2203206
    },
    {
        "id":4,
        "tag": "44439525",
        "name": "订餐须知👨‍🍳",
        "icon": "",
        "big_pic_url": "",
        "current_page": 0,
        "has_next_page": true,
        "product_count": 2,
        "type": 1,
        "selected": 0,
        "tag_description": "",
        "description": "理工广医早上11点开始配送。下午5点开始配送。理工晚上6点50分停止接单。",
        "sequence": 0,
        "activity_tag": "",
        "tags": [],
        "buzType": 0,
        "restaurant_id": 2203206
    },
    {
        "id":5,
        "tag": "29973349",
        "name": "特别推介👉👉",
        "icon": "",
        "big_pic_url": "",
        "current_page": 0,
        "has_next_page": true,
        "product_count": 13,
        "type": 1,
        "selected": 0,
        "tag_description": "",
        "description": "",
        "sequence": 1,
        "activity_tag": "",
        "tags": [],
        "buzType": 0,
        "restaurant_id": 2203206
    },
    {
        "id":6,
        "tag": "29870737",
        "name": "快餐类🍱🍱",
        "icon": "",
        "big_pic_url": "",
        "current_page": 0,
        "has_next_page": true,
        "product_count": 20,
        "type": 1,
        "selected": 0,
        "tag_description": "",
        "description": "",
        "sequence": 2,
        "activity_tag": "",
        "tags": [],
        "buzType": 0,
        "restaurant_id": 2203206
    },
    {
        "id":7,
        "tag": "29941925",
        "name": "招牌煲仔饭🍲🍲",
        "icon": "",
        "big_pic_url": "",
        "current_page": 0,
        "has_next_page": true,
        "product_count": 14,
        "type": 1,
        "selected": 0,
        "tag_description": "",
        "description": "",
        "sequence": 3,
        "activity_tag": "",
        "tags": [],
        "buzType": 0,
        "restaurant_id": 2203206
    },
    {
        "id":8,
        "tag": "29972749",
        "name": "滑蛋类🍳🍳",
        "icon": "",
        "big_pic_url": "",
        "current_page": 0,
        "has_next_page": true,
        "product_count": 4,
        "type": 1,
        "selected": 0,
        "tag_description": "",
        "description": "",
        "sequence": 4,
        "activity_tag": "",
        "tags": [],
        "buzType": 0,
        "restaurant_id": 2203206
    },
    {
        "id":9,
        "tag": "29972774",
        "name": "双拼类🍖🍗",
        "icon": "",
        "big_pic_url": "",
        "current_page": 0,
        "has_next_page": true,
        "product_count": 6,
        "type": 1,
        "selected": 0,
        "tag_description": "",
        "description": "",
        "sequence": 5,
        "activity_tag": "",
        "tags": [],
        "buzType": 0,
        "restaurant_id": 2203206
    },
    {
        "id":10,
        "tag": "29972785",
        "name": "炒饭类😏😏",
        "icon": "",
        "big_pic_url": "",
        "current_page": 0,
        "has_next_page": true,
        "product_count": 4,
        "type": 1,
        "selected": 0,
        "tag_description": "",
        "description": "",
        "sequence": 6,
        "activity_tag": "",
        "tags": [],
        "buzType": 0,
        "restaurant_id": 2203206
    },
    {
        "id":11,
        "tag": "29972914",
        "name": "炒米类🍝🍝",
        "icon": "",
        "big_pic_url": "",
        "current_page": 0,
        "has_next_page": true,
        "product_count": 2,
        "type": 1,
        "selected": 0,
        "tag_description": "",
        "description": "",
        "sequence": 7,
        "activity_tag": "",
        "tags": [],
        "buzType": 0,
        "restaurant_id": 2203206
    },
    {
        "id":12,
        "tag": "34075031",
        "name": "消暑饮料🍹🍹",
        "icon": "",
        "big_pic_url": "",
        "current_page": 0,
        "has_next_page": true,
        "product_count": 6,
        "type": 1,
        "selected": 0,
        "tag_description": "",
        "description": "",
        "sequence": 9,
        "activity_tag": "",
        "tags": [],
        "buzType": 0,
        "restaurant_id": 2203206
    },
    {
        "id":13,
        "tag": "39354009",
        "name": "白饭一盒2元🍚🍚",
        "icon": "",
        "big_pic_url": "",
        "current_page": 0,
        "has_next_page": true,
        "product_count": 1,
        "type": 1,
        "selected": 0,
        "tag_description": "",
        "description": "",
        "sequence": 9,
        "activity_tag": "",
        "tags": [],
        "buzType": 0,
        "restaurant_id": 2203206
    }
]
/*arr.forEach((el)=>{
    let FoodSpuTags_db = new FoodSpuTags(el)
    FoodSpuTags_db.save();
})*/
export default FoodSpuTags;


