import mongoose from 'mongoose'

const Schema = mongoose.Schema;

const foodSpuSchema = new mongoose.Schema({
    id: Number,
    restaurant_id: Number,
    food_spu_sku_tags_id:String,
    name:String,
    min_price:Number,
    praise_num:Number,
    praise_content:String,
    tread_num:Number,
    praise_num_new:Number,
    unit:String,
    description:String,
    picture:String,
    month_saled: Number,
    month_saled_content: String,
    status:Number,
    status_description:String,
    status_remind_list:[],
    attrs:[],
    sku_label:String,
    tag:Number,
    sequence:Number,
    promotion_info:String,
});

const FoodSpu = mongoose.model('FoodSpu', foodSpuSchema);

let arr = [
    {
        "id": 231850711,
        "name": "川香辣子鸡",
        "min_price": 13,
        "praise_num": 2,
        "praise_content": "赞2",
        "tread_num": 2,
        "praise_num_new": 2,
        "unit": "",
        "description": "吃货匹克精神：吃的更多，吃的更饱，吃的更好！",
        "picture": "http://p0.meituan.net/xianfu/4231373db929a5c49dfd84b2e6f1f682427297.jpg.webp",
        "month_saled": 173,
        "month_saled_content": "月售173",
        "status": 0,
        "status_description": "",
        "status_remind_list": [],
        "attrs": [],
        "sku_label": "规格",
        "tag": "29870737",
        "sequence": 0,
        "promotion_info": "",
        "food_spu_sku_tags_id": 1
    },
    {
        "id": 230225591,
        "name": "烧鸭饭",
        "min_price": 9.9,
        "praise_num": 2,
        "praise_content": "赞2",
        "tread_num": 0,
        "praise_num_new": 2,
        "unit": "",
        "description": "对吃货来说，这世上不能吃的就是亏",
        "picture": "http://p1.meituan.net/wmproduct/7f829c871f9a2b34f69ca65d8a514cd466535.jpg.webp",
        "month_saled": 173,
        "month_saled_content": "月售173",
        "status": 0,
        "status_description": "",
        "status_remind_list": [],
        "attrs": [],
        "sku_label": "规格",
        "tag": "29870737",
        "sequence": 0,
        "promotion_info": "5折 限5份",
        "food_spu_sku_tags_id": 1
    },
    {
        "id": 260772977,
        "name": "煎蛋",
        "min_price": 2,
        "praise_num": 4,
        "praise_content": "赞4",
        "tread_num": 2,
        "praise_num_new": 4,
        "unit": "",
        "description": "吃货的座右铭：Just eat it !",
        "picture": "http://p1.meituan.net/xianfu/cda439d2e74ea7de9ac75f780e444bc6356515.jpg.webp",
        "month_saled": 145,
        "month_saled_content": "月售145",
        "status": 0,
        "status_description": "",
        "status_remind_list": [],
        "attrs": [],
        "sku_label": "规格",
        "tag": "29973349",
        "sequence": 0,
        "promotion_info": "",
        "food_spu_sku_tags_id": 1
    },
    {
        "id": 231851910,
        "name": "酸辣鸡杂饭",
        "min_price": 9.9,
        "praise_num": 3,
        "praise_content": "赞3",
        "tread_num": 1,
        "praise_num_new": 3,
        "unit": "",
        "description": "吃得是福，多多益善",
        "picture": "http://p1.meituan.net/xianfu/459c395e7adc2e25b3edc9ae8776a5ce423936.jpg.webp",
        "month_saled": 144,
        "month_saled_content": "月售144",
        "status": 0,
        "status_description": "",
        "status_remind_list": [],
        "attrs": [],
        "sku_label": "规格",
        "tag": "29870737",
        "sequence": 0,
        "promotion_info": "5折 限5份",
        "food_spu_sku_tags_id": 1
    },
    {
        "id": 260769985,
        "name": "可乐",
        "min_price": 3,
        "praise_num": 4,
        "praise_content": "赞4",
        "tread_num": 1,
        "praise_num_new": 4,
        "unit": "",
        "description": "",
        "picture": "http://p0.meituan.net/xianfu/e23c9232b9e70fb8863127714f081450399723.jpg.webp",
        "month_saled": 110,
        "month_saled_content": "月售110",
        "status": 0,
        "status_description": "",
        "status_remind_list": [],
        "attrs": [],
        "sku_label": "规格",
        "tag": "34075031",
        "sequence": 0,
        "promotion_info": "",
        "food_spu_sku_tags_id": 1
    },
    {
        "id": 231835959,
        "name": "火腿滑蛋饭",
        "min_price": 9.9,
        "praise_num": 3,
        "praise_content": "赞3",
        "tread_num": 0,
        "praise_num_new": 3,
        "unit": "",
        "description": "",
        "picture": "http://p0.meituan.net/xianfu/89ee4f8455dccffa9b783665b30f0ce2352737.jpg.webp",
        "month_saled": 102,
        "month_saled_content": "月售102",
        "status": 0,
        "status_description": "",
        "status_remind_list": [],
        "attrs": [],
        "sku_label": "规格",
        "tag": "29972749",
        "sequence": 0,
        "promotion_info": "5折 限5份",
        "food_spu_sku_tags_id": 1
    },
    {
        "id": 231843609,
        "name": "印尼炒饭",
        "min_price": 12,
        "praise_num": 2,
        "praise_content": "赞2",
        "tread_num": 0,
        "praise_num_new": 2,
        "unit": "",
        "description": "",
        "picture": "http://p1.meituan.net/xianfu/aadbdee017d0e99cc0caf8e6086c03a752600.jpg.webp",
        "month_saled": 91,
        "month_saled_content": "月售91",
        "status": 0,
        "status_description": "",
        "status_remind_list": [],
        "attrs": [],
        "sku_label": "规格",
        "tag": "29972785",
        "sequence": 0,
        "promotion_info": "",
        "food_spu_sku_tags_id": 1
    },
    {
        "id": 231838191,
        "name": "鱼香茄子饭",
        "min_price": 12,
        "praise_num": 1,
        "praise_content": "赞1",
        "tread_num": 1,
        "praise_num_new": 1,
        "unit": "",
        "description": "",
        "picture": "http://p0.meituan.net/xianfu/5891cfd1892b74e9ff3ca92ea0857ea1395395.jpg.webp",
        "month_saled": 84,
        "month_saled_content": "月售84",
        "status": 0,
        "status_description": "",
        "status_remind_list": [],
        "attrs": [],
        "sku_label": "规格",
        "tag": "29870737",
        "sequence": 0,
        "promotion_info": "",
        "food_spu_sku_tags_id": 1
    },
    {
        "id": 408237909,
        "name": "鱼香肉丝饭",
        "min_price": 13,
        "praise_num": 0,
        "praise_content": "赞0",
        "tread_num": 1,
        "praise_num_new": 0,
        "unit": "",
        "description": "",
        "picture": "http://p1.meituan.net/xianfu/84d3ecfffc2aa026a7066d35cc417a9c415325.jpg.webp",
        "month_saled": 84,
        "month_saled_content": "月售84",
        "status": 0,
        "status_description": "",
        "status_remind_list": [],
        "attrs": [],
        "sku_label": "规格",
        "tag": "29973349",
        "sequence": 0,
        "promotion_info": "",
        "food_spu_sku_tags_id": 1
    },
    {
        "id": 231844960,
        "name": "菜心肉片饭",
        "min_price": 12,
        "praise_num": 0,
        "praise_content": "赞0",
        "tread_num": 0,
        "praise_num_new": 0,
        "unit": "",
        "description": "",
        "picture": "http://p0.meituan.net/xianfu/8dcc714aa5791d474e0c71f9d04a7e25248172.jpg.webp",
        "month_saled": 65,
        "month_saled_content": "月售65",
        "status": 0,
        "status_description": "",
        "status_remind_list": [],
        "attrs": [],
        "sku_label": "规格",
        "tag": "29870737",
        "sequence": 0,
        "promotion_info": "",
        "food_spu_sku_tags_id": 1
    },
    {
        "id": 231835959,
        "name": "火腿滑蛋饭",
        "min_price": 9.9,
        "praise_num": 3,
        "praise_content": "赞3",
        "tread_num": 0,
        "praise_num_new": 3,
        "unit": "",
        "description": "",
        "picture": "http://p0.meituan.net/xianfu/89ee4f8455dccffa9b783665b30f0ce2352737.jpg.webp",
        "month_saled": 102,
        "month_saled_content": "月售102",
        "status": 0,
        "status_description": "",
        "status_remind_list": [],
        "attrs": [],
        "sku_label": "规格",
        "tag": "29972749",
        "sequence": 0,
        "promotion_info": "5折 限5份",
        "food_spu_sku_tags_id": 2
    },
    {
        "id": 230225591,
        "name": "烧鸭饭",
        "min_price": 9.9,
        "praise_num": 2,
        "praise_content": "赞2",
        "tread_num": 0,
        "praise_num_new": 2,
        "unit": "",
        "description": "对吃货来说，这世上不能吃的就是亏",
        "picture": "http://p1.meituan.net/wmproduct/7f829c871f9a2b34f69ca65d8a514cd466535.jpg.webp",
        "month_saled": 173,
        "month_saled_content": "月售173",
        "status": 0,
        "status_description": "",
        "status_remind_list": [],
        "attrs": [],
        "sku_label": "规格",
        "tag": "29870737",
        "sequence": 0,
        "promotion_info": "5折 限5份",
        "food_spu_sku_tags_id": 2
    },
    {
        "id": 231851910,
        "name": "酸辣鸡杂饭",
        "min_price": 9.9,
        "praise_num": 3,
        "praise_content": "赞3",
        "tread_num": 1,
        "praise_num_new": 3,
        "unit": "",
        "description": "吃得是福，多多益善",
        "picture": "http://p1.meituan.net/xianfu/459c395e7adc2e25b3edc9ae8776a5ce423936.jpg.webp",
        "month_saled": 144,
        "month_saled_content": "月售144",
        "status": 0,
        "status_description": "",
        "status_remind_list": [],
        "attrs": [],
        "sku_label": "规格",
        "tag": "29870737",
        "sequence": 0,
        "promotion_info": "5折 限5份",
        "food_spu_sku_tags_id": 2
    },
    {
        "id": 231841929,
        "name": "烧鸭拼叉烧",
        "min_price": 14,
        "praise_num": 2,
        "praise_content": "赞2",
        "tread_num": 1,
        "praise_num_new": 2,
        "unit": "",
        "description": "",
        "picture": "http://p0.meituan.net/xianfu/d55078ebd6fd325f81eda52c614f2c77336834.jpg.webp",
        "month_saled": 54,
        "month_saled_content": "月售54",
        "status": 0,
        "status_description": "",
        "status_remind_list": [],
        "attrs": [],
        "sku_label": "规格",
        "tag": "29972774",
        "sequence": 0,
        "promotion_info": "买1份赠1份价值两元清凉茶一瓶",
        "food_spu_sku_tags_id": 3
    },
    {
        "id": 495172999,
        "name": "广医早上12：15下单下午6：15前下单",
        "min_price": 0,
        "praise_num": 0,
        "praise_content": "赞0",
        "tread_num": 0,
        "praise_num_new": 0,
        "unit": "",
        "description": "",
        "picture": "http://p0.meituan.net/xianfu/54135a676050c752570f02cd0b5e1633338606.jpg.webp",
        "month_saled": 2,
        "month_saled_content": "月售2",
        "status": 0,
        "status_description": "",
        "status_remind_list": [],
        "attrs": [],
        "sku_label": "规格",
        "tag": "44439525",
        "sequence": 0,
        "promotion_info": "",
        "food_spu_sku_tags_id": 4
    },
    {
        "id": 442954406,
        "name": "理工早上11点开始配送。理工晚上6点50分停止接单。",
        "min_price": 0,
        "praise_num": 1,
        "praise_content": "赞1",
        "tread_num": 0,
        "praise_num_new": 1,
        "unit": "",
        "description": "",
        "picture": "http://p0.meituan.net/xianfu/d7675c6411ab233e4e280fd4ce587a63235023.jpg.webp",
        "month_saled": 1,
        "month_saled_content": "月售1",
        "status": 0,
        "status_description": "",
        "status_remind_list": [],
        "attrs": [],
        "sku_label": "规格",
        "tag": "44439525",
        "sequence": 0,
        "promotion_info": "",
        "food_spu_sku_tags_id": 4
    },
    {
        "id": 495157120,
        "name": "农家一碗香",
        "min_price": 11,
        "praise_num": 1,
        "praise_content": "赞1",
        "tread_num": 0,
        "praise_num_new": 1,
        "unit": "",
        "description": "",
        "picture": "http://p0.meituan.net/xianfu/5265871cc3d79b6cefc0ead63dfb061e344345.jpg.webp",
        "month_saled": 42,
        "month_saled_content": "月售42",
        "status": 0,
        "status_description": "",
        "status_remind_list": [],
        "attrs": [
            {
                "name": "辣度",
                "values": [
                    {
                        "id": 188025818,
                        "value": "微辣"
                    },
                    {
                        "id": 188025819,
                        "value": "中辣"
                    },
                    {
                        "id": 188025820,
                        "value": "大辣"
                    }
                ]
            }
        ],
        "sku_label": "规格",
        "tag": "29973349",
        "sequence": 0,
        "promotion_info": "",
        "food_spu_sku_tags_id": 5
    },
    {
        "id": 495147948,
        "name": "招牌秘制排骨饭",
        "min_price": 11,
        "praise_num": 2,
        "praise_content": "赞2",
        "tread_num": 0,
        "praise_num_new": 2,
        "unit": "",
        "description": "",
        "picture": "http://p1.meituan.net/xianfu/bcd644f754c276adc681b68a30503ee0330074.jpg.webp",
        "month_saled": 51,
        "month_saled_content": "月售51",
        "status": 0,
        "status_description": "",
        "status_remind_list": [],
        "attrs": [],
        "sku_label": "规格",
        "tag": "29973349",
        "sequence": 0,
        "promotion_info": "",
        "food_spu_sku_tags_id": 5
    },
    {
        "id": 495159394,
        "name": "飘香豉油鸡",
        "min_price": 10,
        "praise_num": 0,
        "praise_content": "赞0",
        "tread_num": 1,
        "praise_num_new": 0,
        "unit": "",
        "description": "",
        "picture": "http://p0.meituan.net/xianfu/46552a9b1c56f636dae6941d5a1ae3e4370236.jpg.webp",
        "month_saled": 20,
        "month_saled_content": "月售20",
        "status": 0,
        "status_description": "",
        "status_remind_list": [],
        "attrs": [],
        "sku_label": "规格",
        "tag": "29973349",
        "sequence": 0,
        "promotion_info": "",
        "food_spu_sku_tags_id": 5
    },
    {
        "id": 495159209,
        "name": "潮汕猪肉卷",
        "min_price": 10,
        "praise_num": 1,
        "praise_content": "赞1",
        "tread_num": 0,
        "praise_num_new": 1,
        "unit": "",
        "description": "",
        "picture": "http://p0.meituan.net/xianfu/71959ef8f3a0d7295e116ee365b97f88217031.jpg.webp",
        "month_saled": 13,
        "month_saled_content": "月售13",
        "status": 0,
        "status_description": "",
        "status_remind_list": [],
        "attrs": [],
        "sku_label": "规格",
        "tag": "29973349",
        "sequence": 0,
        "promotion_info": "",
        "food_spu_sku_tags_id": 5
    },
    {
        "id": 454091261,
        "name": "手撕鸡拼黑椒鸡扒",
        "min_price": 14,
        "praise_num": 1,
        "praise_content": "赞1",
        "tread_num": 0,
        "praise_num_new": 1,
        "unit": "",
        "description": "新品",
        "picture": "http://p0.meituan.net/wmproduct/af3ee7e2566f146f5dbbf8aeebec358c550177.jpg.webp",
        "month_saled": 49,
        "month_saled_content": "月售49",
        "status": 0,
        "status_description": "",
        "status_remind_list": [],
        "attrs": [],
        "sku_label": "规格",
        "tag": "29973349",
        "sequence": 0,
        "promotion_info": "",
        "food_spu_sku_tags_id": 5
    },
    {
        "id": 454091205,
        "name": "叉烧拼黑椒鸡扒",
        "min_price": 14,
        "praise_num": 2,
        "praise_content": "赞2",
        "tread_num": 0,
        "praise_num_new": 2,
        "unit": "",
        "description": "新品",
        "picture": "http://p1.meituan.net/wmproduct/510c83162bd94835ec505a4bd92d1383543992.jpg.webp",
        "month_saled": 41,
        "month_saled_content": "月售41",
        "status": 0,
        "status_description": "",
        "status_remind_list": [],
        "attrs": [],
        "sku_label": "规格",
        "tag": "29973349",
        "sequence": 0,
        "promotion_info": "",
        "food_spu_sku_tags_id": 5
    },
    {
        "id": 408237909,
        "name": "鱼香肉丝饭",
        "min_price": 13,
        "praise_num": 0,
        "praise_content": "赞0",
        "tread_num": 1,
        "praise_num_new": 0,
        "unit": "",
        "description": "",
        "picture": "http://p1.meituan.net/xianfu/84d3ecfffc2aa026a7066d35cc417a9c415325.jpg.webp",
        "month_saled": 84,
        "month_saled_content": "月售84",
        "status": 0,
        "status_description": "",
        "status_remind_list": [],
        "attrs": [],
        "sku_label": "规格",
        "tag": "29973349",
        "sequence": 0,
        "promotion_info": "",
        "food_spu_sku_tags_id": 5
    },
    {
        "id": 401722120,
        "name": "川香辣子鸡套餐",
        "min_price": 16,
        "praise_num": 0,
        "praise_content": "赞0",
        "tread_num": 0,
        "praise_num_new": 0,
        "unit": "",
        "description": "川香辣子鸡+加多宝",
        "picture": "http://p0.meituan.net/xianfu/1ec51111873fa5372017cf3f1e4a9ce4415891.jpg.webp",
        "month_saled": 11,
        "month_saled_content": "月售11",
        "status": 0,
        "status_description": "",
        "status_remind_list": [],
        "attrs": [],
        "sku_label": "规格",
        "tag": "29973349",
        "sequence": 0,
        "promotion_info": "",
        "food_spu_sku_tags_id": 5
    },
    {
        "id": 400577703,
        "name": "至尊五宝饭",
        "min_price": 16,
        "praise_num": 1,
        "praise_content": "赞1",
        "tread_num": 0,
        "praise_num_new": 1,
        "unit": "",
        "description": "烧鸭十叉烧十手撕鸡十卤肉十煎蛋",
        "picture": "http://p1.meituan.net/wmproduct/61fef5e283838449dceae88d3f7a0c98102219.jpg.webp",
        "month_saled": 10,
        "month_saled_content": "月售10",
        "status": 0,
        "status_description": "",
        "status_remind_list": [],
        "attrs": [],
        "sku_label": "规格",
        "tag": "29973349",
        "sequence": 0,
        "promotion_info": "",
        "food_spu_sku_tags_id": 5
    },
    {
        "id": 260772977,
        "name": "煎蛋",
        "min_price": 2,
        "praise_num": 4,
        "praise_content": "赞4",
        "tread_num": 2,
        "praise_num_new": 4,
        "unit": "",
        "description": "吃货的座右铭：Just eat it !",
        "picture": "http://p1.meituan.net/xianfu/cda439d2e74ea7de9ac75f780e444bc6356515.jpg.webp",
        "month_saled": 145,
        "month_saled_content": "月售145",
        "status": 0,
        "status_description": "",
        "status_remind_list": [],
        "attrs": [],
        "sku_label": "规格",
        "tag": "29973349",
        "sequence": 0,
        "promotion_info": "",
        "food_spu_sku_tags_id": 5
    },
    {
        "id": 231873497,
        "name": "土豆牛肉饭",
        "min_price": 15,
        "praise_num": 0,
        "praise_content": "赞0",
        "tread_num": 0,
        "praise_num_new": 0,
        "unit": "",
        "description": "",
        "picture": "http://p1.meituan.net/xianfu/4aacf6f7328155eca9ea099da6a5e63d385024.jpg.webp",
        "month_saled": 34,
        "month_saled_content": "月售34",
        "status": 0,
        "status_description": "",
        "status_remind_list": [],
        "attrs": [],
        "sku_label": "规格",
        "tag": "29973349",
        "sequence": 0,
        "promotion_info": "",
        "food_spu_sku_tags_id": 5
    },
    {
        "id": 231875228,
        "name": "沙姜炒滑鸡饭",
        "min_price": 13,
        "praise_num": 0,
        "praise_content": "赞0",
        "tread_num": 1,
        "praise_num_new": 0,
        "unit": "",
        "description": "",
        "picture": "http://p1.meituan.net/xianfu/bdda4329438df01615bfafcfd636d6bf79836.jpg.webp",
        "month_saled": 36,
        "month_saled_content": "月售36",
        "status": 0,
        "status_description": "",
        "status_remind_list": [],
        "attrs": [],
        "sku_label": "规格",
        "tag": "29973349",
        "sequence": 0,
        "promotion_info": "",
        "food_spu_sku_tags_id": 5
    },
    {
        "id": 231875162,
        "name": "海鲜日本豆腐饭",
        "min_price": 14,
        "praise_num": 0,
        "praise_content": "赞0",
        "tread_num": 0,
        "praise_num_new": 0,
        "unit": "",
        "description": "",
        "picture": "http://p1.meituan.net/xianfu/075df45915d7765d03a2515e53216705396362.jpg.webp",
        "month_saled": 23,
        "month_saled_content": "月售23",
        "status": 0,
        "status_description": "",
        "status_remind_list": [],
        "attrs": [],
        "sku_label": "规格",
        "tag": "29973349",
        "sequence": 0,
        "promotion_info": "",
        "food_spu_sku_tags_id": 5
    },
    {
        "id": 231874412,
        "name": "土豆焖鸡饭",
        "min_price": 13,
        "praise_num": 1,
        "praise_content": "赞1",
        "tread_num": 0,
        "praise_num_new": 1,
        "unit": "",
        "description": "",
        "picture": "http://p1.meituan.net/xianfu/227806fa3f3fdb57bba7d2b7fb47dc77448512.jpg.webp",
        "month_saled": 41,
        "month_saled_content": "月售41",
        "status": 0,
        "status_description": "",
        "status_remind_list": [],
        "attrs": [],
        "sku_label": "规格",
        "tag": "29870737",
        "sequence": 0,
        "promotion_info": "",
        "food_spu_sku_tags_id": 6
    },
    {
        "id": 231844029,
        "name": "土豆牛肉饭",
        "min_price": 15,
        "praise_num": 0,
        "praise_content": "赞0",
        "tread_num": 0,
        "praise_num_new": 0,
        "unit": "",
        "description": "",
        "picture": "http://p1.meituan.net/xianfu/4aacf6f7328155eca9ea099da6a5e63d385024.jpg.webp",
        "month_saled": 16,
        "month_saled_content": "月售16",
        "status": 0,
        "status_description": "",
        "status_remind_list": [],
        "attrs": [],
        "sku_label": "规格",
        "tag": "29870737",
        "sequence": 0,
        "promotion_info": "",
        "food_spu_sku_tags_id": 6
    },
    {
        "id": 231835916,
        "name": "农家小炒肉",
        "min_price": 13,
        "praise_num": 0,
        "praise_content": "赞0",
        "tread_num": 0,
        "praise_num_new": 0,
        "unit": "",
        "description": "",
        "picture": "http://p0.meituan.net/xianfu/59229982a8b1d87d8c45a524cc1d0e3d396929.jpg.webp",
        "month_saled": 49,
        "month_saled_content": "月售49",
        "status": 0,
        "status_description": "",
        "status_remind_list": [],
        "attrs": [],
        "sku_label": "规格",
        "tag": "29870737",
        "sequence": 0,
        "promotion_info": "",
        "food_spu_sku_tags_id": 6
    },
    {
        "id": 231850711,
        "name": "川香辣子鸡",
        "min_price": 13,
        "praise_num": 2,
        "praise_content": "赞2",
        "tread_num": 2,
        "praise_num_new": 2,
        "unit": "",
        "description": "吃货匹克精神：吃的更多，吃的更饱，吃的更好！",
        "picture": "http://p0.meituan.net/xianfu/4231373db929a5c49dfd84b2e6f1f682427297.jpg.webp",
        "month_saled": 173,
        "month_saled_content": "月售173",
        "status": 0,
        "status_description": "",
        "status_remind_list": [],
        "attrs": [],
        "sku_label": "规格",
        "tag": "29870737",
        "sequence": 0,
        "promotion_info": "",
        "food_spu_sku_tags_id": 6
    },
    {
        "id": 231845576,
        "name": "榨菜肉片饭",
        "min_price": 12,
        "praise_num": 1,
        "praise_content": "赞1",
        "tread_num": 0,
        "praise_num_new": 1,
        "unit": "",
        "description": "",
        "picture": "http://p1.meituan.net/xianfu/80bd7c06be544c6c09b20dabc74c90ae366273.jpg.webp",
        "month_saled": 16,
        "month_saled_content": "月售16",
        "status": 0,
        "status_description": "",
        "status_remind_list": [],
        "attrs": [],
        "sku_label": "规格",
        "tag": "29870737",
        "sequence": 0,
        "promotion_info": "",
        "food_spu_sku_tags_id": 6
    },
    {
        "id": 231845550,
        "name": "莲藕肉片饭",
        "min_price": 12,
        "praise_num": 0,
        "praise_content": "赞0",
        "tread_num": 0,
        "praise_num_new": 0,
        "unit": "",
        "description": "",
        "picture": "http://p1.meituan.net/xianfu/6f18aead8ef6243ee8ebe843d581fc07359564.jpg.webp",
        "month_saled": 17,
        "month_saled_content": "月售17",
        "status": 0,
        "status_description": "",
        "status_remind_list": [],
        "attrs": [],
        "sku_label": "规格",
        "tag": "29870737",
        "sequence": 0,
        "promotion_info": "",
        "food_spu_sku_tags_id": 6
    },
    {
        "id": 231844960,
        "name": "菜心肉片饭",
        "min_price": 12,
        "praise_num": 0,
        "praise_content": "赞0",
        "tread_num": 0,
        "praise_num_new": 0,
        "unit": "",
        "description": "",
        "picture": "http://p0.meituan.net/xianfu/8dcc714aa5791d474e0c71f9d04a7e25248172.jpg.webp",
        "month_saled": 65,
        "month_saled_content": "月售65",
        "status": 0,
        "status_description": "",
        "status_remind_list": [],
        "attrs": [],
        "sku_label": "规格",
        "tag": "29870737",
        "sequence": 0,
        "promotion_info": "",
        "food_spu_sku_tags_id": 6
    },
    {
        "id": 231844930,
        "name": "茄汁鸡扒饭",
        "min_price": 13,
        "praise_num": 1,
        "praise_content": "赞1",
        "tread_num": 0,
        "praise_num_new": 1,
        "unit": "",
        "description": "",
        "picture": "http://p0.meituan.net/xianfu/2dcd2ae92e1d7e0050a84628429889ac278764.jpg.webp",
        "month_saled": 14,
        "month_saled_content": "月售14",
        "status": 0,
        "status_description": "",
        "status_remind_list": [],
        "attrs": [],
        "sku_label": "规格",
        "tag": "29870737",
        "sequence": 0,
        "promotion_info": "",
        "food_spu_sku_tags_id": 6
    },
    {
        "id": 231846741,
        "name": "黑椒鸡扒饭",
        "min_price": 13,
        "praise_num": 0,
        "praise_content": "赞0",
        "tread_num": 0,
        "praise_num_new": 0,
        "unit": "",
        "description": "",
        "picture": "http://p0.meituan.net/xianfu/0571bc0757393e0ac63b04f0283d299b318416.jpg.webp",
        "month_saled": 13,
        "month_saled_content": "月售13",
        "status": 0,
        "status_description": "",
        "status_remind_list": [],
        "attrs": [],
        "sku_label": "规格",
        "tag": "29870737",
        "sequence": 0,
        "promotion_info": "",
        "food_spu_sku_tags_id": 6
    },
    {
        "id": 231846440,
        "name": "香菇滑鸡饭",
        "min_price": 13,
        "praise_num": 0,
        "praise_content": "赞0",
        "tread_num": 0,
        "praise_num_new": 0,
        "unit": "",
        "description": "",
        "picture": "http://p1.meituan.net/xianfu/d4bceeeb04afe14c92cf572bd01754d9385362.jpg.webp",
        "month_saled": 8,
        "month_saled_content": "月售8",
        "status": 0,
        "status_description": "",
        "status_remind_list": [],
        "attrs": [],
        "sku_label": "规格",
        "tag": "29870737",
        "sequence": 0,
        "promotion_info": "",
        "food_spu_sku_tags_id": 6
    },
    {
        "id": 231838671,
        "name": "双菇炒肉片饭",
        "min_price": 12,
        "praise_num": 2,
        "praise_content": "赞2",
        "tread_num": 0,
        "praise_num_new": 2,
        "unit": "",
        "description": "",
        "picture": "http://p1.meituan.net/xianfu/c88ca553d44b49fae8e02a9a25e1e1fa42682.jpg.webp",
        "month_saled": 23,
        "month_saled_content": "月售23",
        "status": 0,
        "status_description": "",
        "status_remind_list": [],
        "attrs": [],
        "sku_label": "规格",
        "tag": "29870737",
        "sequence": 0,
        "promotion_info": "",
        "food_spu_sku_tags_id": 6
    },
    {
        "id": 231842659,
        "name": "酸辣土豆丝",
        "min_price": 12,
        "praise_num": 0,
        "praise_content": "赞0",
        "tread_num": 0,
        "praise_num_new": 0,
        "unit": "",
        "description": "",
        "picture": "http://p0.meituan.net/xianfu/d2b52442ad8d098d94801b621648edb241514.jpg.webp",
        "month_saled": 12,
        "month_saled_content": "月售12",
        "status": 0,
        "status_description": "",
        "status_remind_list": [],
        "attrs": [],
        "sku_label": "规格",
        "tag": "29870737",
        "sequence": 0,
        "promotion_info": "",
        "food_spu_sku_tags_id": 6
    },
    {
        "id": 231842624,
        "name": "土豆肉片饭",
        "min_price": 12,
        "praise_num": 0,
        "praise_content": "赞0",
        "tread_num": 0,
        "praise_num_new": 0,
        "unit": "",
        "description": "",
        "picture": "http://p0.meituan.net/xianfu/72c98dd70790510d8ef77891ccd9fd5c360753.jpg.webp",
        "month_saled": 40,
        "month_saled_content": "月售40",
        "status": 0,
        "status_description": "",
        "status_remind_list": [],
        "attrs": [],
        "sku_label": "规格",
        "tag": "29870737",
        "sequence": 0,
        "promotion_info": "",
        "food_spu_sku_tags_id": 6
    },
    {
        "id": 231838191,
        "name": "鱼香茄子饭",
        "min_price": 12,
        "praise_num": 1,
        "praise_content": "赞1",
        "tread_num": 1,
        "praise_num_new": 1,
        "unit": "",
        "description": "",
        "picture": "http://p0.meituan.net/xianfu/5891cfd1892b74e9ff3ca92ea0857ea1395395.jpg.webp",
        "month_saled": 84,
        "month_saled_content": "月售84",
        "status": 0,
        "status_description": "",
        "status_remind_list": [],
        "attrs": [],
        "sku_label": "规格",
        "tag": "29870737",
        "sequence": 0,
        "promotion_info": "",
        "food_spu_sku_tags_id": 6
    },
    {
        "id": 231843178,
        "name": "红烧茄子饭",
        "min_price": 12,
        "praise_num": 1,
        "praise_content": "赞1",
        "tread_num": 0,
        "praise_num_new": 1,
        "unit": "",
        "description": "",
        "picture": "http://p0.meituan.net/xianfu/701e0ad4fcf81f0b2fce95a5f45023f8412461.jpg.webp",
        "month_saled": 20,
        "month_saled_content": "月售20",
        "status": 0,
        "status_description": "",
        "status_remind_list": [],
        "attrs": [],
        "sku_label": "规格",
        "tag": "29870737",
        "sequence": 0,
        "promotion_info": "",
        "food_spu_sku_tags_id": 6
    },
    {
        "id": 231838129,
        "name": "凉瓜炒牛肉饭",
        "min_price": 15,
        "praise_num": 2,
        "praise_content": "赞2",
        "tread_num": 0,
        "praise_num_new": 2,
        "unit": "",
        "description": "",
        "picture": "http://p0.meituan.net/xianfu/e723ea118662f85cd86b8ccd3b131eaf66762.jpg.webp",
        "month_saled": 19,
        "month_saled_content": "月售19",
        "status": 0,
        "status_description": "",
        "status_remind_list": [],
        "attrs": [],
        "sku_label": "规格",
        "tag": "29870737",
        "sequence": 0,
        "promotion_info": "",
        "food_spu_sku_tags_id": 6
    },
    {
        "id": 231842118,
        "name": "手撕鸡饭",
        "min_price": 13,
        "praise_num": 0,
        "praise_content": "赞0",
        "tread_num": 0,
        "praise_num_new": 0,
        "unit": "",
        "description": "",
        "picture": "http://p1.meituan.net/xianfu/49d405a4b015699584078a4530066d7b440602.jpg.webp",
        "month_saled": 26,
        "month_saled_content": "月售26",
        "status": 0,
        "status_description": "",
        "status_remind_list": [],
        "attrs": [],
        "sku_label": "规格",
        "tag": "29870737",
        "sequence": 0,
        "promotion_info": "",
        "food_spu_sku_tags_id": 6
    },
    {
        "id": 230232369,
        "name": "叉烧饭",
        "min_price": 12,
        "praise_num": 0,
        "praise_content": "赞0",
        "tread_num": 0,
        "praise_num_new": 0,
        "unit": "",
        "description": "",
        "picture": "http://p1.meituan.net/wmproduct/1e7e527cad689ca12dd8261af2b211df68537.jpg.webp",
        "month_saled": 10,
        "month_saled_content": "月售10",
        "status": 0,
        "status_description": "",
        "status_remind_list": [],
        "attrs": [],
        "sku_label": "规格",
        "tag": "29870737",
        "sequence": 0,
        "promotion_info": "",
        "food_spu_sku_tags_id": 6
    },
    {
        "id": 231865441,
        "name": "火腿 排骨 香菇 肉饼",
        "min_price": 14,
        "praise_num": 0,
        "praise_content": "赞0",
        "tread_num": 0,
        "praise_num_new": 0,
        "unit": "",
        "description": "",
        "picture": "http://p0.meituan.net/xianfu/85ba6bd096359f8f242b4065def2ec04403805.jpg.webp",
        "month_saled": 6,
        "month_saled_content": "月售6",
        "status": 0,
        "status_description": "",
        "status_remind_list": [],
        "attrs": [],
        "sku_label": "规格",
        "tag": "29941925",
        "sequence": 0,
        "promotion_info": "",
        "food_spu_sku_tags_id": 7
    },
    {
        "id": 231860297,
        "name": "火腿 玉米 鸡肉 肉丸",
        "min_price": 14,
        "praise_num": 0,
        "praise_content": "赞0",
        "tread_num": 0,
        "praise_num_new": 0,
        "unit": "",
        "description": "",
        "picture": "http://p1.meituan.net/xianfu/93b5182d81e8857c9e7e0a4a04edd6d9243469.jpg.webp",
        "month_saled": 13,
        "month_saled_content": "月售13",
        "status": 0,
        "status_description": "",
        "status_remind_list": [],
        "attrs": [],
        "sku_label": "规格",
        "tag": "29941925",
        "sequence": 0,
        "promotion_info": "",
        "food_spu_sku_tags_id": 7
    },
    {
        "id": 231866113,
        "name": "鸡肾 香菇 排骨 肉饼",
        "min_price": 14,
        "praise_num": 0,
        "praise_content": "赞0",
        "tread_num": 0,
        "praise_num_new": 0,
        "unit": "",
        "description": "",
        "picture": "http://p0.meituan.net/xianfu/6df7857bd7499d22ac4f44c18062ddef87116.jpg.webp",
        "month_saled": 5,
        "month_saled_content": "月售5",
        "status": 0,
        "status_description": "",
        "status_remind_list": [],
        "attrs": [],
        "sku_label": "规格",
        "tag": "29941925",
        "sequence": 0,
        "promotion_info": "",
        "food_spu_sku_tags_id": 7
    },
    {
        "id": 231860225,
        "name": "排骨 香菇 肉丸 鸡肉",
        "min_price": 14,
        "praise_num": 0,
        "praise_content": "赞0",
        "tread_num": 0,
        "praise_num_new": 0,
        "unit": "",
        "description": "",
        "picture": "http://p0.meituan.net/xianfu/968b7e58e4a79a9e8158a8b9a4abb21f335438.jpg.webp",
        "month_saled": 38,
        "month_saled_content": "月售38",
        "status": 0,
        "status_description": "",
        "status_remind_list": [],
        "attrs": [],
        "sku_label": "规格",
        "tag": "29941925",
        "sequence": 0,
        "promotion_info": "",
        "food_spu_sku_tags_id": 7
    },
    {
        "id": 231858502,
        "name": "腊肉 香菇 火腿 肉饼",
        "min_price": 14,
        "praise_num": 0,
        "praise_content": "赞0",
        "tread_num": 0,
        "praise_num_new": 0,
        "unit": "",
        "description": "",
        "picture": "http://p0.meituan.net/xianfu/76198bf17e75d834c71c234371e4770b387307.jpg.webp",
        "month_saled": 4,
        "month_saled_content": "月售4",
        "status": 0,
        "status_description": "",
        "status_remind_list": [],
        "attrs": [],
        "sku_label": "规格",
        "tag": "29941925",
        "sequence": 0,
        "promotion_info": "",
        "food_spu_sku_tags_id": 7
    },
    {
        "id": 231862756,
        "name": "香菇 肉饼 鸡肾 瘦肉",
        "min_price": 14,
        "praise_num": 0,
        "praise_content": "赞0",
        "tread_num": 0,
        "praise_num_new": 0,
        "unit": "",
        "description": "",
        "picture": "http://p1.meituan.net/xianfu/023636bfd328503614468d9594a43508359255.jpg.webp",
        "month_saled": 8,
        "month_saled_content": "月售8",
        "status": 0,
        "status_description": "",
        "status_remind_list": [],
        "attrs": [],
        "sku_label": "规格",
        "tag": "29941925",
        "sequence": 0,
        "promotion_info": "",
        "food_spu_sku_tags_id": 7
    },
    {
        "id": 231862637,
        "name": "玉米 香菇 鸡肉 排骨",
        "min_price": 14,
        "praise_num": 0,
        "praise_content": "赞0",
        "tread_num": 0,
        "praise_num_new": 0,
        "unit": "",
        "description": "",
        "picture": "http://p0.meituan.net/xianfu/de3fa5c46fdd15116af8ce8023eb7ecc415701.jpg.webp",
        "month_saled": 6,
        "month_saled_content": "月售6",
        "status": 0,
        "status_description": "",
        "status_remind_list": [],
        "attrs": [],
        "sku_label": "规格",
        "tag": "29941925",
        "sequence": 0,
        "promotion_info": "",
        "food_spu_sku_tags_id": 7
    },
    {
        "id": 231863421,
        "name": "香菇 鸡肉 玉米 叉烧",
        "min_price": 14,
        "praise_num": 0,
        "praise_content": "赞0",
        "tread_num": 0,
        "praise_num_new": 0,
        "unit": "",
        "description": "",
        "picture": "http://p0.meituan.net/xianfu/cc79f333808484096ceb9c108b36f0d7368200.jpg.webp",
        "month_saled": 6,
        "month_saled_content": "月售6",
        "status": 0,
        "status_description": "",
        "status_remind_list": [],
        "attrs": [],
        "sku_label": "规格",
        "tag": "29941925",
        "sequence": 0,
        "promotion_info": "",
        "food_spu_sku_tags_id": 7
    },
    {
        "id": 231862304,
        "name": "瘦肉 玉米 粉肠 猪肝",
        "min_price": 14,
        "praise_num": 0,
        "praise_content": "赞0",
        "tread_num": 1,
        "praise_num_new": 0,
        "unit": "",
        "description": "",
        "picture": "http://p1.meituan.net/xianfu/d1954da42ca7f176b49ce9ef7f1995db471040.jpg.webp",
        "month_saled": 21,
        "month_saled_content": "月售21",
        "status": 0,
        "status_description": "",
        "status_remind_list": [],
        "attrs": [],
        "sku_label": "规格",
        "tag": "29941925",
        "sequence": 0,
        "promotion_info": "",
        "food_spu_sku_tags_id": 7
    },
    {
        "id": 231862050,
        "name": "腊肉 肉丸 鸡肾 排骨",
        "min_price": 14,
        "praise_num": 1,
        "praise_content": "赞1",
        "tread_num": 0,
        "praise_num_new": 1,
        "unit": "",
        "description": "",
        "picture": "http://p1.meituan.net/xianfu/2e9bcb1590b5c79d804a73f0583029df326349.jpg.webp",
        "month_saled": 14,
        "month_saled_content": "月售14",
        "status": 0,
        "status_description": "",
        "status_remind_list": [],
        "attrs": [],
        "sku_label": "规格",
        "tag": "29941925",
        "sequence": 0,
        "promotion_info": "",
        "food_spu_sku_tags_id": 7
    },
    {
        "id": 231858101,
        "name": "鸡肾 鸡肉 肉丸 玉米",
        "min_price": 14,
        "praise_num": 0,
        "praise_content": "赞0",
        "tread_num": 0,
        "praise_num_new": 0,
        "unit": "",
        "description": "",
        "picture": "http://p0.meituan.net/xianfu/cc79f333808484096ceb9c108b36f0d7368200.jpg.webp",
        "month_saled": 10,
        "month_saled_content": "月售10",
        "status": 0,
        "status_description": "",
        "status_remind_list": [],
        "attrs": [],
        "sku_label": "规格",
        "tag": "29941925",
        "sequence": 0,
        "promotion_info": "",
        "food_spu_sku_tags_id": 7
    },
    {
        "id": 231861764,
        "name": "腊肠 瘦肉 玉米 肉丸",
        "min_price": 14,
        "praise_num": 0,
        "praise_content": "赞0",
        "tread_num": 0,
        "praise_num_new": 0,
        "unit": "",
        "description": "",
        "picture": "http://p1.meituan.net/xianfu/6f6c5173bb2685e8a0667fa1774a5335366864.jpg.webp",
        "month_saled": 19,
        "month_saled_content": "月售19",
        "status": 0,
        "status_description": "",
        "status_remind_list": [],
        "attrs": [],
        "sku_label": "规格",
        "tag": "29941925",
        "sequence": 0,
        "promotion_info": "",
        "food_spu_sku_tags_id": 7
    },
    {
        "id": 231855545,
        "name": "腊肠 叉烧 瘦肉 腊肉",
        "min_price": 14,
        "praise_num": 0,
        "praise_content": "赞0",
        "tread_num": 0,
        "praise_num_new": 0,
        "unit": "",
        "description": "",
        "picture": "http://p0.meituan.net/xianfu/475a9a0fcd3cd78ad1af69efa6369228211474.jpg.webp",
        "month_saled": 27,
        "month_saled_content": "月售27",
        "status": 0,
        "status_description": "",
        "status_remind_list": [],
        "attrs": [],
        "sku_label": "规格",
        "tag": "29941925",
        "sequence": 0,
        "promotion_info": "",
        "food_spu_sku_tags_id": 7
    },
    {
        "id": 231853920,
        "name": "腊肠 叉烧 瘦肉 玉米",
        "min_price": 14,
        "praise_num": 1,
        "praise_content": "赞1",
        "tread_num": 0,
        "praise_num_new": 1,
        "unit": "",
        "description": "",
        "picture": "http://p1.meituan.net/xianfu/af540120251062ef42b7626e85132fbb363862.jpg.webp",
        "month_saled": 12,
        "month_saled_content": "月售12",
        "status": 0,
        "status_description": "",
        "status_remind_list": [],
        "attrs": [],
        "sku_label": "规格",
        "tag": "29941925",
        "sequence": 0,
        "promotion_info": "",
        "food_spu_sku_tags_id": 7
    },
    {
        "id": 231849533,
        "name": "叉烧滑蛋饭",
        "min_price": 13,
        "praise_num": 0,
        "praise_content": "赞0",
        "tread_num": 0,
        "praise_num_new": 0,
        "unit": "",
        "description": "",
        "picture": "http://p1.meituan.net/xianfu/4b46470a24b54ca3d2b472107ae30290279019.jpg.webp",
        "month_saled": 6,
        "month_saled_content": "月售6",
        "status": 0,
        "status_description": "",
        "status_remind_list": [],
        "attrs": [],
        "sku_label": "规格",
        "tag": "29972749",
        "sequence": 0,
        "promotion_info": "",
        "food_spu_sku_tags_id": 8
    },
    {
        "id": 231838744,
        "name": "牛肉滑蛋饭",
        "min_price": 15,
        "praise_num": 0,
        "praise_content": "赞0",
        "tread_num": 1,
        "praise_num_new": 0,
        "unit": "",
        "description": "",
        "picture": "http://p0.meituan.net/xianfu/182d180a3f7c06be352363c7b66d28a7312689.jpg.webp",
        "month_saled": 17,
        "month_saled_content": "月售17",
        "status": 0,
        "status_description": "",
        "status_remind_list": [],
        "attrs": [],
        "sku_label": "规格",
        "tag": "29972749",
        "sequence": 0,
        "promotion_info": "",
        "food_spu_sku_tags_id": 8
    },
    {
        "id": 231843292,
        "name": "肉片滑蛋饭",
        "min_price": 12,
        "praise_num": 1,
        "praise_content": "赞1",
        "tread_num": 0,
        "praise_num_new": 1,
        "unit": "",
        "description": "",
        "picture": "http://p0.meituan.net/xianfu/aade5a9f476fe56231d51bffe2a0069b381637.jpg.webp",
        "month_saled": 13,
        "month_saled_content": "月售13",
        "status": 0,
        "status_description": "",
        "status_remind_list": [],
        "attrs": [],
        "sku_label": "规格",
        "tag": "29972749",
        "sequence": 0,
        "promotion_info": "",
        "food_spu_sku_tags_id": 8
    },
    {
        "id": 231872218,
        "name": "手撕鸡拼豉油鸡",
        "min_price": 14,
        "praise_num": 0,
        "praise_content": "赞0",
        "tread_num": 0,
        "praise_num_new": 0,
        "unit": "",
        "description": "",
        "picture": "http://p0.meituan.net/xianfu/46552a9b1c56f636dae6941d5a1ae3e4370236.jpg.webp",
        "month_saled": 8,
        "month_saled_content": "月售8",
        "status": 0,
        "status_description": "",
        "status_remind_list": [],
        "attrs": [],
        "sku_label": "规格",
        "tag": "29972774",
        "sequence": 0,
        "promotion_info": "",
        "food_spu_sku_tags_id": 9
    },
    {
        "id": 231872141,
        "name": "叉烧拼台湾卤肉",
        "min_price": 14,
        "praise_num": 1,
        "praise_content": "赞1",
        "tread_num": 0,
        "praise_num_new": 1,
        "unit": "",
        "description": "",
        "picture": "http://p0.meituan.net/xianfu/4e2f134d0d7e718f03fd0fe92b179bce477184.jpg.webp",
        "month_saled": 9,
        "month_saled_content": "月售9",
        "status": 0,
        "status_description": "",
        "status_remind_list": [],
        "attrs": [],
        "sku_label": "规格",
        "tag": "29972774",
        "sequence": 0,
        "promotion_info": "",
        "food_spu_sku_tags_id": 9
    },
    {
        "id": 231872039,
        "name": "豉油鸡拼手撕鸡",
        "min_price": 14,
        "praise_num": 0,
        "praise_content": "赞0",
        "tread_num": 0,
        "praise_num_new": 0,
        "unit": "",
        "description": "",
        "picture": "http://p0.meituan.net/xianfu/af6eded6406fb9f7a4697ae791575ff3469435.jpg.webp",
        "month_saled": 6,
        "month_saled_content": "月售6",
        "status": 0,
        "status_description": "",
        "status_remind_list": [],
        "attrs": [],
        "sku_label": "规格",
        "tag": "29972774",
        "sequence": 0,
        "promotion_info": "",
        "food_spu_sku_tags_id": 9
    },
    {
        "id": 231845435,
        "name": "卤水鸡腿拼叉烧",
        "min_price": 14,
        "praise_num": 0,
        "praise_content": "赞0",
        "tread_num": 0,
        "praise_num_new": 0,
        "unit": "",
        "description": "",
        "picture": "http://p1.meituan.net/xianfu/77e96bc1777fdc0e2387f4e89b65c000176220.jpg.webp",
        "month_saled": 1,
        "month_saled_content": "月售1",
        "status": 0,
        "status_description": "",
        "status_remind_list": [],
        "attrs": [],
        "sku_label": "规格",
        "tag": "29972774",
        "sequence": 0,
        "promotion_info": "",
        "food_spu_sku_tags_id": 9
    },
    {
        "id": 231841999,
        "name": "酸辣鸡杂套餐",
        "min_price": 19,
        "praise_num": 0,
        "praise_content": "赞0",
        "tread_num": 0,
        "praise_num_new": 0,
        "unit": "",
        "description": "酸辣鸡杂饭加可乐",
        "picture": "http://p0.meituan.net/xianfu/d23e6340319c0591f59428b0c4bf2406355143.jpg.webp",
        "month_saled": 7,
        "month_saled_content": "月售7",
        "status": 0,
        "status_description": "",
        "status_remind_list": [],
        "attrs": [],
        "sku_label": "规格",
        "tag": "29972774",
        "sequence": 0,
        "promotion_info": "",
        "food_spu_sku_tags_id": 9
    },
    {
        "id": 334038755,
        "name": "牛肉炒饭",
        "min_price": 13,
        "praise_num": 3,
        "praise_content": "赞3",
        "tread_num": 0,
        "praise_num_new": 3,
        "unit": "",
        "description": "",
        "picture": "http://p0.meituan.net/xianfu/0ab146afd667184d841930aad38b3c8d417849.jpg.webp",
        "month_saled": 28,
        "month_saled_content": "月售28",
        "status": 0,
        "status_description": "",
        "status_remind_list": [],
        "attrs": [],
        "sku_label": "规格",
        "tag": "29972785",
        "sequence": 0,
        "promotion_info": "",
        "food_spu_sku_tags_id": 10
    },
    {
        "id": 231842081,
        "name": "扬州炒饭",
        "min_price": 11,
        "praise_num": 1,
        "praise_content": "赞1",
        "tread_num": 0,
        "praise_num_new": 1,
        "unit": "",
        "description": "",
        "picture": "http://p0.meituan.net/xianfu/e4dcc720abd032be2b6b28be3c4a4c7644735.jpg.webp",
        "month_saled": 33,
        "month_saled_content": "月售33",
        "status": 0,
        "status_description": "",
        "status_remind_list": [],
        "attrs": [],
        "sku_label": "规格",
        "tag": "29972785",
        "sequence": 0,
        "promotion_info": "",
        "food_spu_sku_tags_id": 10
    },
    {
        "id": 231835505,
        "name": "杂锦炒饭",
        "min_price": 11,
        "praise_num": 1,
        "praise_content": "赞1",
        "tread_num": 0,
        "praise_num_new": 1,
        "unit": "",
        "description": "",
        "picture": "http://p0.meituan.net/xianfu/a241a66c743ccab1c31d611fb7e823f6376163.jpg.webp",
        "month_saled": 15,
        "month_saled_content": "月售15",
        "status": 0,
        "status_description": "",
        "status_remind_list": [],
        "attrs": [],
        "sku_label": "规格",
        "tag": "29972785",
        "sequence": 0,
        "promotion_info": "",
        "food_spu_sku_tags_id": 10
    },
    {
        "id": 231843609,
        "name": "印尼炒饭",
        "min_price": 12,
        "praise_num": 2,
        "praise_content": "赞2",
        "tread_num": 0,
        "praise_num_new": 2,
        "unit": "",
        "description": "",
        "picture": "http://p1.meituan.net/xianfu/aadbdee017d0e99cc0caf8e6086c03a752600.jpg.webp",
        "month_saled": 91,
        "month_saled_content": "月售91",
        "status": 0,
        "status_description": "",
        "status_remind_list": [],
        "attrs": [],
        "sku_label": "规格",
        "tag": "29972785",
        "sequence": 0,
        "promotion_info": "",
        "food_spu_sku_tags_id": 10
    },
    {
        "id": 231839701,
        "name": "星州炒米",
        "min_price": 12,
        "praise_num": 0,
        "praise_content": "赞0",
        "tread_num": 0,
        "praise_num_new": 0,
        "unit": "",
        "description": "",
        "picture": "http://p0.meituan.net/xianfu/86c7701fec343910f1d5d784b174771770314.jpg.webp",
        "month_saled": 17,
        "month_saled_content": "月售17",
        "status": 0,
        "status_description": "",
        "status_remind_list": [],
        "attrs": [],
        "sku_label": "规格",
        "tag": "29972914",
        "sequence": 0,
        "promotion_info": "",
        "food_spu_sku_tags_id": 11
    },
    {
        "id": 231839666,
        "name": "台式三鲜炒米",
        "min_price": 12,
        "praise_num": 1,
        "praise_content": "赞1",
        "tread_num": 0,
        "praise_num_new": 1,
        "unit": "",
        "description": "",
        "picture": "http://p0.meituan.net/xianfu/512c612258ea1674f594dcba8cc823c5318758.jpg.webp",
        "month_saled": 46,
        "month_saled_content": "月售46",
        "status": 0,
        "status_description": "",
        "status_remind_list": [],
        "attrs": [],
        "sku_label": "规格",
        "tag": "29972914",
        "sequence": 0,
        "promotion_info": "",
        "food_spu_sku_tags_id": 11
    },
    {
        "id": 407209263,
        "name": "维他奶",
        "min_price": 3,
        "praise_num": 0,
        "praise_content": "赞0",
        "tread_num": 0,
        "praise_num_new": 0,
        "unit": "",
        "description": "",
        "picture": "http://p1.meituan.net/wmproduct/c8d4358359ce3678202262c44244286a320569.jpg.webp",
        "month_saled": 35,
        "month_saled_content": "月售35",
        "status": 0,
        "status_description": "",
        "status_remind_list": [],
        "attrs": [],
        "sku_label": "规格",
        "tag": "34075031",
        "sequence": 0,
        "promotion_info": "",
        "food_spu_sku_tags_id": 12
    },
    {
        "id": 299273383,
        "name": "加多宝",
        "min_price": 4,
        "praise_num": 0,
        "praise_content": "赞0",
        "tread_num": 0,
        "praise_num_new": 0,
        "unit": "",
        "description": "",
        "picture": "http://p1.meituan.net/wmproduct/81d4e84214a7012b3094e081d777ab2f332063.jpg.webp",
        "month_saled": 15,
        "month_saled_content": "月售15",
        "status": 0,
        "status_description": "",
        "status_remind_list": [],
        "attrs": [],
        "sku_label": "规格",
        "tag": "34075031",
        "sequence": 0,
        "promotion_info": "",
        "food_spu_sku_tags_id": 12
    },
    {
        "id": 260769985,
        "name": "可乐",
        "min_price": 3,
        "praise_num": 4,
        "praise_content": "赞4",
        "tread_num": 1,
        "praise_num_new": 4,
        "unit": "",
        "description": "",
        "picture": "http://p0.meituan.net/xianfu/e23c9232b9e70fb8863127714f081450399723.jpg.webp",
        "month_saled": 110,
        "month_saled_content": "月售110",
        "status": 0,
        "status_description": "",
        "status_remind_list": [],
        "attrs": [],
        "sku_label": "规格",
        "tag": "34075031",
        "sequence": 0,
        "promotion_info": "",
        "food_spu_sku_tags_id": 12
    },
    {
        "id": 260774628,
        "name": "雪碧",
        "min_price": 3,
        "praise_num": 2,
        "praise_content": "赞2",
        "tread_num": 0,
        "praise_num_new": 2,
        "unit": "",
        "description": "",
        "picture": "http://p0.meituan.net/xianfu/b90fadf96c69e32462af3a8119c6bdbe449468.jpg.webp",
        "month_saled": 21,
        "month_saled_content": "月售21",
        "status": 0,
        "status_description": "",
        "status_remind_list": [],
        "attrs": [],
        "sku_label": "规格",
        "tag": "34075031",
        "sequence": 0,
        "promotion_info": "",
        "food_spu_sku_tags_id": 12
    },
    {
        "id": 264098196,
        "name": "清凉茶",
        "min_price": 1,
        "praise_num": 0,
        "praise_content": "赞0",
        "tread_num": 1,
        "praise_num_new": 0,
        "unit": "",
        "description": "",
        "picture": "http://p0.meituan.net/xianfu/daab97811f695ef5a040ccaf3a088943385024.jpg.webp",
        "month_saled": 27,
        "month_saled_content": "月售27",
        "status": 0,
        "status_description": "",
        "status_remind_list": [],
        "attrs": [],
        "sku_label": "规格",
        "tag": "34075031",
        "sequence": 0,
        "promotion_info": "",
        "food_spu_sku_tags_id": 12
    },
    {
        "id": 271253738,
        "name": "菊花茶",
        "min_price": 1,
        "praise_num": 1,
        "praise_content": "赞1",
        "tread_num": 1,
        "praise_num_new": 1,
        "unit": "",
        "description": "",
        "picture": "http://p0.meituan.net/xianfu/f3a742c355bebee0c1941c35ac0168a7378880.jpg.webp",
        "month_saled": 32,
        "month_saled_content": "月售32",
        "status": 0,
        "status_description": "",
        "status_remind_list": [],
        "attrs": [],
        "sku_label": "规格",
        "tag": "34075031",
        "sequence": 0,
        "promotion_info": "",
        "food_spu_sku_tags_id": 12
    },
    {
        "id": 408244922,
        "name": "白饭",
        "min_price": 2,
        "praise_num": 0,
        "praise_content": "赞0",
        "tread_num": 0,
        "praise_num_new": 0,
        "unit": "",
        "description": "",
        "picture": "http://p0.meituan.net/xianfu/587b63f301a47cba360b07a383f863e1237872.jpg.webp",
        "month_saled": 20,
        "month_saled_content": "月售20",
        "status": 0,
        "status_description": "",
        "status_remind_list": [],
        "attrs": [],
        "sku_label": "规格",
        "tag": "39354009",
        "sequence": 0,
        "promotion_info": "",
        "food_spu_sku_tags_id": 13
    }
]
/*arr.forEach((el)=>{
    let FoodSpuSk_db = new FoodSpu(el)
    FoodSpuSk_db.save();
})*/

export default FoodSpu;
